/**
 * Cross-implementation signature checks.
 *
 * Every other test in this directory builds its fixture with the same formula the
 * verifier applies, which proves the code is self-consistent and nothing more — a
 * misreading of a provider's spec would be baked into fixture and verifier alike and
 * both would pass. These tests instead have the provider's own SDK produce the
 * signature, so the assertion is "we agree with Stripe/Svix", not "we agree with us".
 *
 * Only providers that ship a signing routine can be covered this way. The rest need a
 * captured real request; see the coverage note at the bottom of this file.
 */
import { describe, expect, it } from "vitest";
import Stripe from "stripe";
import { Webhook } from "svix";
import { verifySignature } from "./index";

const URL_ = "https://in.anyhook.net/u/app";

/**
 * stripe-node types every option as required, while the implementation defaults
 * timestamp and scheme and derives the signature itself. Passing a blank `signature`
 * to satisfy the type would make it sign nothing, so the cast is narrowed to here.
 */
function stripeTestHeader(stripe: Stripe, payload: string, secret: string): string {
  type Opts = Parameters<typeof stripe.webhooks.generateTestHeaderString>[0];
  return stripe.webhooks.generateTestHeaderString({ payload, secret } as unknown as Opts);
}

describe("cross-check: signatures produced by the provider's own SDK", () => {
  it("accepts a header generated by stripe-node", async () => {
    const stripe = new Stripe("sk_test_" + "0".repeat(24), { apiVersion: "2025-09-30.clover" });
    const payload = JSON.stringify({ id: "evt_1", type: "charge.succeeded" });
    const secret = "whsec_" + "s".repeat(32);

    const header = stripeTestHeader(stripe, payload, secret);

    expect(
      await verifySignature("stripe", new Headers({ "stripe-signature": header }), payload, secret, URL_)
    ).toBe(true);
  });

  it("rejects a stripe-node header when the body is altered in flight", async () => {
    const stripe = new Stripe("sk_test_" + "0".repeat(24), { apiVersion: "2025-09-30.clover" });
    const payload = JSON.stringify({ id: "evt_1", amount: 100 });
    const secret = "whsec_" + "s".repeat(32);

    const header = stripeTestHeader(stripe, payload, secret);
    const tampered = JSON.stringify({ id: "evt_1", amount: 999999 });

    expect(
      await verifySignature("stripe", new Headers({ "stripe-signature": header }), tampered, secret, URL_)
    ).toBe(false);
  });

  it("accepts a signature generated by the svix SDK", async () => {
    const secret = "whsec_" + Buffer.from("k".repeat(24)).toString("base64");
    const payload = JSON.stringify({ type: "email.received", data: { subject: "hi" } });
    const msgId = "msg_crosscheck";
    const ts = new Date();

    const signature = new Webhook(secret).sign(msgId, ts, payload);
    const headers = new Headers({
      "svix-id": msgId,
      "svix-timestamp": Math.floor(ts.getTime() / 1000).toString(),
      "svix-signature": signature,
    });

    expect(await verifySignature("svix", headers, payload, secret, URL_)).toBe(true);
  });

  it("applies the same svix result to clerk and resend", async () => {
    // Both ride Svix infrastructure, so a single implementation backs all three. If
    // that ever diverges, this is the test that says so.
    const secret = "whsec_" + Buffer.from("k".repeat(24)).toString("base64");
    const payload = JSON.stringify({ type: "email.received" });
    const msgId = "msg_crosscheck2";
    const ts = new Date();

    const signature = new Webhook(secret).sign(msgId, ts, payload);
    const headers = new Headers({
      "svix-id": msgId,
      "svix-timestamp": Math.floor(ts.getTime() / 1000).toString(),
      "svix-signature": signature,
    });

    for (const provider of ["svix", "clerk", "resend"] as const) {
      expect(await verifySignature(provider, headers, payload, secret, URL_)).toBe(true);
    }
  });

  it("rejects a svix signature when the body is altered in flight", async () => {
    const secret = "whsec_" + Buffer.from("k".repeat(24)).toString("base64");
    const payload = JSON.stringify({ to: ["me@example.com"] });
    const msgId = "msg_crosscheck3";
    const ts = new Date();

    const signature = new Webhook(secret).sign(msgId, ts, payload);
    const headers = new Headers({
      "svix-id": msgId,
      "svix-timestamp": Math.floor(ts.getTime() / 1000).toString(),
      "svix-signature": signature,
    });

    expect(
      await verifySignature("resend", headers, JSON.stringify({ to: ["attacker@evil.com"] }), secret, URL_)
    ).toBe(false);
  });
});

/**
 * Not cross-checked, and why:
 *
 *   stripe, svix, clerk, resend  ✅ covered above by the provider's own SDK
 *   github, shopify, slack, sentry, linear, vercel, paddle, sendgrid, twilio,
 *   intercom                     — self-consistent tests only (index.test.ts)
 *   discord, hubspot, woocommerce, lemonsqueezy, paypal  — no positive test at all
 *
 * Closing the rest means capturing one real signed request per provider and freezing
 * the (headers, body, secret) triple as a fixture. That is the only evidence that
 * proves agreement for providers with no public signing routine.
 */
